### ISSUE TITLE
Location: Route 2

### ISSUE THREAD

**Issue by TurnipGuy30** [Pokemon-PythonRed/Pokemon-PythonRed#108]

**Comment by nasserkessas** [comment]
I am working on this and on the Viridian Forest at the moment.

Some updates:

+ I merged Viridian-n and -s and added the gym (but it can't be accessed yet anyway)
+ I was thinking of making Route 2 into two parts; South and North (North is the right half of Route 2 which cannot be accessed without Cut) and having Route 2 South connect to Viridian Forest South and Route 2 North

**Comment by nasserkessas** [comment]
Update:
+ Route 2 is now three parts; South (which you enter from Viridian City) which leads to Route 2 (West) and the Viridian Forest and North which comes after Viridian Forest.
+ Viridian Forest is in 4 sections to resemble its maze-like structure like as follows:
```
                 Route 2 (N)
                      |
              Viridian Forest (N)
              /               \
Viridian Forest (W)  ---  Viridian Forest (E)
             \                /
              Viridian Forest (S)
                     |
                  Route 2 (S)
```
