### ISSUE TITLE
All-Contributors

### ISSUE THREAD

**Issue by TurnipGuy30** [Pokemon-PythonRed/Pokemon-PythonRed#13]
@all-contributors please add @TurnipGuy30 for code, data, ideas, maintenance, platform, test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @TurnipGuy30 for code, data, ideas, maintenance, platform, test

**Comment by TurnipGuy30** [comment]
WHAT?! That's amazing!

**Comment by TurnipGuy30** [comment]
@all-contributors please add @hacking-mudkip for ideas, data

**Comment by TurnipGuy30** [comment]
@all-contributors please add @Valensce for maintenance

**Comment by TurnipGuy30** [comment]
@all-contributors please add @JBYT27 for code, mentoring, test, infra

**Comment by TurnipGuy30** [comment]
@all-contributors please add @LaHonathon for design, test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @Valerimatical for design

**Comment by TurnipGuy30** [comment]
@all-contributors please add @jeremyLARDENOIS for testing, platform

**Comment by TurnipGuy30** [comment]
@all-contributors please add @Porsce for design

**Comment by JBYT27** [comment]
Haha nice!

**Comment by TurnipGuy30** [comment]
@JBT27 Yeah, I think it's amazing how easy they made it!

**Comment by TurnipGuy30** [comment]
@all-contributors please add @Isabel-Lifu for ideas, design

**Comment by TurnipGuy30** [comment]
@all-contributors please add @MuLKy-bot for test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @basedpainnn for test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @Specialist-Mathematics for test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @jeremyLARDENOIS for code, mentoring

**Comment by TurnipGuy30** [comment]
@all-contributors please add @all-contributors for documentation

**Comment by TurnipGuy30** [comment]
@all-contributors please add @dependabot for infra

**Comment by TurnipGuy30** [comment]
@all-contributors please add @Valensce for code, design, ideas, tests

**Comment by TurnipGuy30** [comment]
@all-contributors please add @Ravanger101 for test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @sourcery-ai for code

**Comment by TurnipGuy30** [comment]
@all-contributors please add @actions for code, doc, infra, test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @stger040 for test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @fnando for code, tool

**Comment by TurnipGuy30** [comment]
@all-contributors please add @cweijan for plugin

**Comment by TurnipGuy30** [comment]
@all-contributors please add @nilsjpwerner for code, tool

**Comment by TurnipGuy30** [comment]
@all-contributors please add @shanalikhan for plugin, tool

**Comment by TurnipGuy30** [comment]
@all-contributors please add @ionutvmi for code, tool

**Comment by TurnipGuy30** [comment]
@all-contributors please add @Ravanger101 for code

**Comment by TurnipGuy30** [comment]
@all-contributors please add @joeblownn for test

**Comment by TurnipGuy30** [comment]
@all-contributors please add @nasserkessas for code, test

**Comment by Ravanger101** [comment]
Sure @TurnipGuy30

**Comment by TurnipGuy30** [comment]
@Ravanger101 hey there, it's been a while! I'm gonna email you my Discord.

**Comment by Ravanger101** [comment]
No Problem!

**Comment by Ravanger101** [comment]
@TurnipGuy30   I Challenge you to find an Easter Egg in my **Website**!
