### ISSUE TITLE
[ENHANCEMENT] Change contributor order

### ISSUE THREAD

**Issue by JBYT27** [Pokemon-PythonRed/Pokemon-PythonRed#22]
# Hiya!

I just wanted to let you know that you can switch the contributors order in the table by going into the file .all-contributorsrc, and then switching the braces order. Let me know if you need any help with that, but I just wanted to let you know that that’s possible :D

**Comment by TurnipGuy30** [comment]
Hey, thanks for the help! I did figure that was possible, but for the moment, I've got it set to `"contributorsSortAlphabetically": true`, so I don't need to rearrange them.

**Comment by JBYT27** [comment]
Oh, okay! No problem!
