### ISSUE TITLE
Colours for move/Pokemon types

### ISSUE THREAD

**Issue by nasserkessas** [Pokemon-PythonRed/Pokemon-PythonRed#77]
**Feature Description**:

When a Pokemon is mentioned or uses a move, I was thinking they could be coloured according to their type (e.g. Fire type move/Pokemon is red etc.) using ANSI escape codes. <br>
This would look something like this:
![image](https://user-images.githubusercontent.com/59720679/200116434-2e791fc8-e2d9-4845-96c0-976191b3c1b2.png)
and this:
![image](https://user-images.githubusercontent.com/59720679/200116400-3d865262-a1ed-40d4-ae3d-0035351b8cec.png)

If [moves are incorporated into the game](https://github.com/Pokemon-PythonRed/Pokemon-PythonRed/discussions/76), the move type could be coloured as well.

If you choose to do this, I can submit a PR right away (I have the code already which I used to make the images)

**Additional Information**:
For this to work on Windows as well I had to add the line `system("")`. If I submit the PR, I can't really check if it works on Windows so you might have to do that for me

- [ ] I **decline** to being added to the Contributors list.

Thanks for considering this :)

**Comment by TurnipGuy30** [comment]
Great idea, I'll test this now.

**Comment by TurnipGuy30** [comment]
I love this idea! Please do make a PR; I can tweak anything if needed. Thank you!
