### ISSUE TITLE
Internal Error after blacking out

### ISSUE THREAD

**Issue by nasserkessas** [Pokemon-PythonRed/Pokemon-PythonRed#80]
**Bug Description**:
When the player blacks out, the player is transported back to the most recent Pokemon centre they went to. However, if they black out before reaching a pokemon centre, the `save['recentCentre']` flag is still `Null` causing the game to have an Internal Error.

Output:
```
Charmander fainted!
...
NASSER blacked out!

Charmander was healed to max health.




- - - INTERNAL ERROR - - -

ERROR MESSAGE: The location "None" is not a valid location.

If you have not edited any files, feel free to create an issue on the repository by going to the link below.

Note: your save file will be preserved in the program folder. Any unsaved progress will be lost (sorry).

[https://github.com/Pokemon-PythonRed/Pokemon-PythonRed/issues/new/choose]

Press Enter to exit.

> 
```

**Steps To Reproduce**:
After receiving the starter Pokemon from Prof. OAK, go back and forth between Route 1 (North) and Route 1 (South) without stopping at the Viridian City Pokemon Centre to black out. This should reproduce the error.

**Expected Behaviour**:
I'm actually not sure what is supposed to happen in the real Pokemon Red, but I'm guessing you would be taken back to the player's house. You can just decide what you'd like to happen.

**Context**:

 - Python Version:  Python 3.8.10 64-bit

 - PPR Version: Latest commit

**Additional Information**:
Also, when a player blacks out, in Pokemon Red, they [lose half of their money](https://bulbapedia.bulbagarden.net/wiki/Black_out). This is not the case in PPR but is a simple fix.

- [ ] I **decline** to being added to the Contributors list.

**Comment by TurnipGuy30** [comment]
Your guess was correct; it should take the player back to their house. I believe this is fixed in https://github.com/Pokemon-PythonRed/Pokemon-PythonRed/commit/1bd5ec95fc2fa244981eef2a91be27271cbd086c.

**Comment by nasserkessas** [comment]
Yes it is, I'm also submitting a PR for the [money loss](https://github.com/Pokemon-PythonRed/Pokemon-PythonRed/pull/81) problem

**Comment by TurnipGuy30** [comment]
I believe I implemented the loss of money in *trainer* battles (which aren't yet available), but I've never heard of losing money in encounters. Nice catch!
