### ISSUE TITLE
No option to go back to battle menu after selecting 'Attack'

### ISSUE THREAD

**Issue by nasserkessas** [Pokemon-PythonRed/Pokemon-PythonRed#85]
**Bug Description**:

This is not really a bug but when you choose `Attack` there is no way to go back, say if you changed your mind.

**Steps To Reproduce**:

Just start a normal battle with a wild Pokémon like this:

```
What should Charmander do?

[1] - Attack
[2] - Switch
[3] - Item
[4] - Run

> 1

[1] - SCRATCH | NORMAL - 35/35
[2] - GROWL   | NORMAL - 40/40
[3] - EMBER   | FIRE   - 25/25

> e
> q
>      
```

**Expected Behaviour**:

I think there should be a back option that takes you back to the battle menu. I'm not sure if this was done with the other options because at this stage in the game, none of them can be picked.

**Context**:

 - Python Version: 3.8.10 64-bit

 - PPR Version: latest commit

- [ ] I **decline** to being added to the Contributors list.
<br>
Thanks for having a look

**Comment by TurnipGuy30** [comment]
@nasserkessas To be honest, I'm not sure how to implement a `Back` option with the current script. The `Attack` option runs a different function and I don't know how to make it go back. Could you please take a look? Sorry if this is inconvenient for you.

**Comment by nasserkessas** [comment]
@TurnipGuy30 I have submitted a PR to fix this problem. Thanks for having a look
