### ISSUE TITLE
Escape from battle crash

### ISSUE THREAD

**Issue by nasserkessas** [Pokemon-PythonRed/Pokemon-PythonRed#89]
**Bug Description**:
When the player escapes from a wild Pokémon battle, the game crashes.

**Steps To Reproduce**:
- Start a battle with a wild Pokémon 
- Keep trying to escape
- Bug occurs when escape is successful

```
What should Charmander do?

[1] - Attack
[2] - Switch
[3] - Item
[4] - Run

> 4
You escaped!



- - - INTERNAL ERROR - - -

ERROR MESSAGE: 
Invalid battle state; neither won, lost, nor escaped. Could not load player turn.

If you have not edited any files, feel free to create an issue on the repository by going to the link below.

Note: your save file will be preserved in the program folder. Any unsaved progress will be lost (sorry).

[https://github.com/Pokemon-PythonRed/Pokemon-PythonRed/issues/new/choose]

Press Enter to exit.

> 

$ 
```

**Expected Behaviour**:
I'm assuming the battle should just end as it already printed `You escaped!`.

**Context**:

 - Python Version: 3.8.10 64-bit

 - PPR Version: latest commit

- [ ] I **decline** to being added to the Contributors list.

I'll have a look into this.

**Comment by nasserkessas** [comment]
It was a quick fix, just had to change an `if` to an `elif`. I'll make a PR.

**Comment by TurnipGuy30** [comment]
Thanks for finding small bugs like this.

**Comment by nasserkessas** [comment]
No problem!

**Comment by TurnipGuy30** [comment]
> ```
> ERROR MESSAGE: 
> Invalid battle state; neither won, lost, nor escaped. Could not load player turn.
> ```

At least I know the effort I went to writing error messages wasn't wasted.

**Comment by nasserkessas** [comment]
Did my fix not work? It seemed to work for me. And yes, the messages were very useful.
How did you get that error?
