### ISSUE TITLE
Encounter levels and chances

### ISSUE THREAD

**Issue by nasserkessas** [Pokemon-PythonRed/Pokemon-PythonRed#91]
**Feature Description**:

Currently, the encounter rates and levels are equally likely for each Pokémon and level:
```python
battle([Pokemon(choice(['PIDGEY', 'SPEAROW', 'RATTATA', 'BELLSPROUT']), randint(1, 5), 'random')])
```

However, in the real game, encounters and levels are decided from a table like the following (for the tall grass in Route 1):
| Encounter chance | Percentage(approx.) | Pokemon     |
|---------------------|------------------------|-------------|
| 51/256                  | 20%                           | Pidgey Lv.3 |
| 51/256                  | 20%                           | Rattata Lv.3 |
| 39/256                  | 15%                           | Rattata Lv.3 |
| 25/256                  | 10%                           | Rattata Lv.2 |
| 25/256                  | 10%                           | Pidgey Lv.2 |
| 25/256                  | 10%                           | Pidgey Lv.3 |
| 13/256                  | 5%                             | Pidgey Lv.3 |
| 13/256                  | 5%                             | Rattata Lv.4 |
| 11/256                  | 4%                             | Pidgey Lv.4 |
| 3/256                    | 1%                             | Pidgey Lv.5 |

**Implementation ideas**:
I was thinking this could be done by having a `.json` file with all the locations in Kanto and their encounter tables

**Reasoning**:
This would make the game more interesting, more like the real Pokémon Red and help clean up the `main.py` file.

**Additional Information**:
Tables can be found [here](https://gamefaqs.gamespot.com/gameboy/367023-pokemon-red-version/faqs/64175/encounter-tables).

- [ ] I **decline** to being added to the Contributors list.

<br>

I'll work on this when I get some time

**Comment by TurnipGuy30** [comment]
I'd definitely appreciate if you could implement this, it's an awesome idea!

**Comment by nasserkessas** [comment]
This will have to be updated from [here](https://gamefaqs.gamespot.com/gameboy/367023-pokemon-red-version/faqs/64175/encounter-tables) when more locations will be added into the game
