### ISSUE TITLE
ONGOING: Game content/events

### ISSUE THREAD

**Issue by nasserkessas** [Pokemon-PythonRed/Pokemon-PythonRed#97]
**Feature Description**:
This is not really a feature and should probably be changed to a project later on.
Reference this issue for pull requests which add more content to the game.

**Comment by nasserkessas** [comment]
I was thinking we could keep this issue open for further commits but I suppose I'll just create issues for each

**Comment by nasserkessas** [comment]
Could you make one? I don't think with my permissions I can

**Comment by TurnipGuy30** [comment]
https://github.com/orgs/Pokemon-PythonRed/projects/4
